from pathlib import Path
from typing import Dict, Any, List, Optional
from datetime import datetime

from core.data_manager import DataManager

try:
    from fpdf import FPDF
    FPDF_AVAILABLE = True
except ImportError:  # pragma: no cover
    FPDF_AVAILABLE = False


class ReportGenerator:
    """Builds the 'Save report pdf' artifact from a pipeline summary,
    including the NLP coaching feedback generated by
    core/feedback_generator.py (Section 16.4's FeedbackGenerator)."""

    @staticmethod
    def build_pdf(summary: Dict[str, Any], vehicle: Dict[str, Any],
                   feedback_items: Optional[List[str]] = None,
                   driving_persona: Optional[str] = None,
                   fer: Optional[float] = None,
                   filename: str = "driving_coach_report.pdf") -> Path:
        out_path = DataManager.OUTPUTS_DIR / filename
        feedback_items = feedback_items or []

        if not FPDF_AVAILABLE:
            # Minimal text fallback so the flow never hard-fails if fpdf2
            # isn't installed yet.
            out_path = out_path.with_suffix(".txt")
            with open(out_path, "w", encoding="utf-8") as f:
                f.write(ReportGenerator._as_text(summary, vehicle, feedback_items, driving_persona, fer))
            return out_path

        pdf = FPDF()
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 18)
        pdf.cell(0, 12, "Driving Coach Report", ln=True)
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 8, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True)
        pdf.ln(4)

        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 10, "Vehicle", ln=True)
        pdf.set_font("Helvetica", "", 11)
        pdf.cell(0, 8, f"Name: {vehicle.get('car_name', 'N/A')}", ln=True)
        pdf.cell(0, 8, f"Car ID: {vehicle.get('car_id', 'N/A')}", ln=True)
        pdf.cell(0, 8, f"Top RPM: {vehicle.get('top_rpm', 'N/A')}", ln=True)
        pdf.cell(0, 8, f"Top Speed: {vehicle.get('top_speed', 'N/A')}", ln=True)
        pdf.cell(0, 8, f"Max Engine RPM: {vehicle.get('max_engine_rpm', 'N/A')}", ln=True)
        pdf.cell(0, 8, f"Max Suspension Load: {vehicle.get('max_suspension_load', 'N/A')}", ln=True)
        pdf.cell(0, 8, f"Peak Power RPM: {vehicle.get('peak_power_rpm', 'N/A')}", ln=True)
        pdf.ln(4)

        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 10, "Session Summary", ln=True)
        pdf.set_font("Helvetica", "", 11)
        if driving_persona:
            pdf.cell(0, 8, f"Driving persona: {driving_persona}", ln=True)
        if fer is not None:
            pdf.cell(0, 8, f"Feedback Event Rate: {fer} items/lap", ln=True)
        pdf.cell(0, 8, f"Analysis windows: {summary.get('total_windows', 0)}", ln=True)
        pdf.cell(0, 8, f"Flagged windows: {summary.get('flagged_windows', 0)}", ln=True)
        top_speed = summary.get("top_speed_kmh")
        if top_speed is not None:
            pdf.cell(0, 8, f"Top speed recorded: {top_speed:.1f} km/h", ln=True)
        pdf.cell(0, 8, f"Most frequent finding: {summary.get('top_event') or 'Smooth Driving'}", ln=True)
        pdf.ln(4)

        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 10, "Detected Event Breakdown", ln=True)
        pdf.set_font("Helvetica", "", 11)
        for event, count in summary.get("event_counts", {}).items():
            pdf.cell(0, 8, f"- {event}: {count}", ln=True)
        pdf.ln(4)

        pdf.set_font("Helvetica", "B", 13)
        pdf.cell(0, 10, "Coaching Feedback", ln=True)
        pdf.set_font("Helvetica", "", 11)
        if feedback_items:
            for item in feedback_items:
                pdf.multi_cell(0, 7, f"- {item}")
                pdf.ln(1)
        else:
            pdf.cell(0, 8, "No issues flagged above threshold this session - clean driving.", ln=True)

        pdf.output(str(out_path))
        return out_path

    @staticmethod
    def _as_text(summary, vehicle, feedback_items: List[str],
                 driving_persona: Optional[str], fer: Optional[float]) -> str:
        lines = [
            "DRIVING COACH REPORT",
            f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
            "",
            f"Vehicle: {vehicle.get('car_name', 'N/A')}",
            f"Car ID: {vehicle.get('car_id', 'N/A')}",
            f"Top RPM: {vehicle.get('top_rpm', 'N/A')}",
            f"Top Speed: {vehicle.get('top_speed', 'N/A')}",
            f"Max Engine RPM: {vehicle.get('max_engine_rpm', 'N/A')}",
            f"Max Suspension Load: {vehicle.get('max_suspension_load', 'N/A')}",
            f"Peak Power RPM: {vehicle.get('peak_power_rpm', 'N/A')}",
            "",
        ]
        if driving_persona:
            lines.append(f"Driving persona: {driving_persona}")
        if fer is not None:
            lines.append(f"Feedback Event Rate: {fer} items/lap")
        lines += [
            f"Analysis windows: {summary.get('total_windows', 0)}",
            f"Flagged windows: {summary.get('flagged_windows', 0)}",
            f"Most frequent finding: {summary.get('top_event') or 'Smooth Driving'}",
            "",
            "Detected Event Breakdown:",
        ]
        for event, count in summary.get("event_counts", {}).items():
            lines.append(f"- {event}: {count}")

        lines.append("")
        lines.append("Coaching Feedback:")
        if feedback_items:
            for item in feedback_items:
                lines.append(f"- {item}")
        else:
            lines.append("No issues flagged above threshold this session - clean driving.")

        return "\n".join(lines)
