"""
Shared dataclasses and type definitions used across collection, labelling,
preprocessing, fusion, and the desktop app.
"""

from dataclasses import dataclass
from enum import Enum


class TrackName(Enum):
    NURBURGRING_NORDSCHLEIFE = "nurburgring_nordschleife"
    LE_MANS = "circuit_de_la_sarthe"
    KYALAMI = "kyalami_grand_prix_circuit"
    ZWARTKOPS = "zwartkops_raceway"


class WeatherCondition(Enum):
    CLEAR = "clear"
    OVERCAST = "overcast"
    WET = "wet"


class VehicleClass(Enum):
    PRODUCTION_SEDAN = "production_sedan"
    PRODUCTION_HATCHBACK = "production_hatchback"
    GT3_CUP_CAR = "gt3_cup_car"


class DrivingPersona(Enum):
    AGGRESSIVE = "aggressive"
    SMOOTH = "smooth"
    CAUTIOUS = "cautious"


@dataclass
class SessionMetadata:
    """Metadata describing a single recorded simulator session."""
    session_id: str
    track: TrackName
    vehicle_class: VehicleClass
    weather: WeatherCondition
    lap_count: int
    recorded_at: str  # ISO 8601 timestamp


@dataclass
class TelemetryRow:
    """Single row of telemetry as exported by Telemetrick."""
    timestamp_ms: int
    brake_pressure: float
    wheel_speed_fl: float
    wheel_speed_fr: float
    wheel_speed_rl: float
    wheel_speed_rr: float
    wheel_slip_fl: float
    wheel_slip_fr: float
    wheel_slip_rl: float
    wheel_slip_rr: float
    throttle_position: float
    steering_angle: float
    engine_rpm: float
    gear: int
    lateral_g: float
    longitudinal_g: float
    track_position_normalized: float


@dataclass
class SpatialPrediction:
    """CNN module output per proposal §3.5.3 — three binary spatial classes."""
    apex_hit: bool
    within_track_limits: bool
    vehicle_stable: bool


@dataclass
class TemporalPrediction:
    """LSTM module output per proposal §3.5.4 — seven binary telemetry classes."""
    brake_locked: bool
    wheel_spin: bool
    trail_brake: bool
    aggressive_downshift: bool
    late_upshift: bool
    rough_steering: bool
    gentle_acceleration: bool


@dataclass
class FeedbackItem:
    """Single coaching feedback entry generated by the SHAP/template layer."""
    lap_number: int
    turn_number: int
    event_type: str
    message: str
    confidence: float
